### ISSUE TITLE
LMS Toolkit Loader NULL email address error

### ISSUE THREAD

**Issue by stephenfuqua** [Ed-Fi-Exchange-OSS/LMS-Toolkit#360]
Submitted by an end user via Jira:

> I get an error when running the LMS Toolkit Loader regarding NULL email address. Data is still loaded into the SQL DB, but only up to a certain user. The execution attempts to repeat twice and then fails.

**Comment by Ed-Fi-Owner** [comment]
Commenting on this issue as Ed-Fi-Owner, which is not a member of ZenHub. Want to see how it comes through.
